"""add owner_id and shared_orchestrators

Revision ID: 92d1b51f7535
Revises: 915e8a74fe90
Create Date: 2026-03-20 12:19:10.544075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d1b51f7535'
down_revision: Union[str, Sequence[str], None] = '915e8a74fe90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_orchestrators',
    sa.Column('orchestrator_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['orchestrators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('orchestrator_id', 'user_id')
    )
    op.add_column('orchestrators', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orchestrators', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orchestrators', type_='foreignkey')
    op.drop_column('orchestrators', 'owner_id')
    op.drop_table('shared_orchestrators')
    # ### end Alembic commands ###
